### PR TITLE
Translation in french

### PR DESCRIPTION
**Pull request by amalpeyre**

### CODE REVIEW

**Comment by amalpeyre** [comment]
Hello,

It is'nt possible to merge this translation ?

Thx

**Comment by dg0yt** [comment]
Don't worry, I will handle this as soon as time permits.

**Comment by amalpeyre** [comment]
Perfect .

Thx !

**Comment by dg0yt** [comment]
You can now edit the translation on https://hosted.weblate.org/projects/openorienteering/mapper/fr/ now. Just register/login with your Github account.

**Pull request merged**
