### PR TITLE
Mobile UI enhancements

### PR DESCRIPTION
**Pull request by lpechacek**
Two practical enhancements recently tested in the field. I'm willing to update manual pages if they get merged.

For now, mapping (fieldwork) zoom level is fixed at 1:2. While this is an established practice for forest maps, it may not make sense for sprint maps.

### CODE REVIEW

**Comment by lpechacek** [comment]
Thanks, Kai, for reviewing the patches and catching the run-away .orig file. I'll push updated patches soon.

Ad "GPS". While searching I could not find a common understandable term for position fix. The most precise would IMO be "satellite navigation position fix" but who would get the meaning. Next one is "(GNSS) position fix" but it sounds much like expert term. Following the Android trace and trying to figure out what terminology Android developers use I pushed the Google button and the first result took me to Android tutorial about [Making Your App Location-Aware](https://developer.android.com/training/location/change-location-settings.html). Sadly the first sentence refers to "GPS". [Next one](https://support.google.com/nexus/answer/6179507?hl=en) also talks about "GPS" in the "Device only" mode. IIRC, the same wording is in my Android 7 Location services setting dialog. Therefore I'm for keeping "GPS" on the UI side until we have a commonly understood term.

On the code side, there is already over 330 occurrences of "gps" string in origin/master and 10 files containing with "gps" in its name. While I'm in favor of adopting a more generic name, switching the naming convention only with this commit would be inconsistent. I'm willing to do the renames when there is consensus about the terms to use.

Ad Icon. I like the idea. The current one is a combination of the Pan tool icon (the four blue arrows) and Mapper's position fix symbol (red arrow in the middle). While the current icon is in line with Mapper's outlook, the location graphical idiom might be more understandable for newcomers.

Ad zoom levels. "2x zoom" and "1x zoom" is aligned with the zoom level info toast display. I'd like to keep the word "zoom" in the menu entry to make it larger and therefore easier to hit with stylus. Plain "2x" and "1x" might be too tiny for field work. I'll change the strings.

Regarding 2:1 magnification, it turned out to be useful in my practice as a overmapping prevention. While my device has about 290 PPI and can render 1:15 000 map with amazing details at first glance, 1x is incomparable with printed map and is not legible enough. 2x zoom level turned out to be useful for getting clearer view of the surveyed area. In my current work 2x represents a good compromise between "legible" and "showing the context". I'd be happy to hear other user's voices. If I'm not mistaken @mlerjen had an opinion about fieldwork map scale.

**Comment by lpechacek** [comment]
related
* issue #949 - New command request - zoom in on gps position
* issue #1005 - Android: Definable "mapping scale" for field work

**Comment by dg0yt** [comment]
I already used a more common location icon for the "Copy coordinates" pie menu action:

https://github.com/OpenOrienteering/mapper/blob/master/images/copy-coords.png

**Comment by ollesmaps** [comment]
Ad "GPS" - just word "Position" might be suitable enough.

**Comment by dg0yt** [comment]
zoom-action-changes


This proposed change is certainly very useful. But how to deal with regarding v0.8.0 (which still needs updates to [Mapper app manual page](http://www.openorienteering.org/mapper-manual/pages/android-app.html) anyway)? I would like to see/do a few modifications.

Major:
- The actions "Record temporary GPS trace", "Record temporary GPS position", and "Clear temporary GPS markers" need to remain grouped together.

Minor:
- Indeed, I prefer the general term "position".
- I would like to change the position-/track-related icons (standard position marker instead of triangle).
- The zoom-out popup menu could include the "whole map" action from the top bar. When removing the "whole map" button from the top bar, the grid button could move to the position above the map parts button.

Anyway, position/sensor related actions remain scattered over three corners of the screen (top left, bottom left, bottom right).

**Comment by ollesmaps** [comment]
I never use actions "Record temporary GPS trace", "Record temporary GPS position", and "Clear temporary GPS markers". This might be because I use a lot the scribbling into bitmap tool.  I wonder if anybody is a heavy user of this?

**Comment by ollesmaps** [comment]
This relates to #952 where "Show whole map - this button shall be rather in the down left corner, where zooming occurs" was also mentioned.

**Comment by dg0yt** [comment]
"Reversed drop" was the word I was looking for :-)

I can't say much about "Record temporary GPS trace", "Record temporary GPS position", and "Clear temporary GPS markers". As I already said at the of my last post, the position features need consolidation, but its out of scope for v0.8.0 / #1028.

Important is to
 - not make the mobile UI even worse.
 - get the UI strings to be translated right, early.

Given that I have this branch checked out the moment I can add a commit with my adjustments for further review.

**Comment by dg0yt** [comment]
Actually, Android now uses the term "location" in its [API](https://developer.android.com/reference/android/location/Location.html). But there is no text anyway in the Android button:

screenshot

**Comment by mlerjen** [comment]
Sorry the question, but where are versions to test?

**Comment by dg0yt** [comment]
There are no downloads which include this change. I'm waiting for feedback from lpechacek. As soon as I can merge the change, I will update the documentation page and start building the v0.8.0 release (candidate).

**Comment by ollesmaps** [comment]
I would argue that making incremantal changes is better than a sudden overhall of UI. Moving buttons within a region is a very small change. It can be tested only in unstable versions. This way we get feedback.

**Comment by dg0yt** [comment]
If this is a minor change, it should be fine to release it (soon) with the next stable build which is v08.0. If it is considered a major change, it won't be in v0.8.0. There is [litte reason](https://github.com/OpenOrienteering/mapper/compare/v0.7.93...master) to provide another preview before v0.8.0.

**Comment by lpechacek** [comment]
Sorry for delayed response - was out sick and kept away from computers in general.

@dg0yt: Good point about icon grouping. I didn't notice it as I made some more changes in my devel branch which shadowed the discrepancy. I also like the term "my location" and the proposal of moving over to "reversed drop" graphical idiom. With that I'm all fine with commit 19454b6.

Regarding the mobile UI as whole, I agree with @ollesmaps that it needs a serious overhaul. While I have made [some more changes](https://github.com/lpechacek/mapper/commits/mobile-ui-gadgets) which I'm happily using in the field, I'm not offering them for merge yet. IMO a big-bang change in direction of mlerjen's proposal in #534 is a better course of action than incremental rework.

**Comment by dg0yt** [comment]
@lpechacek Glad to hear you are back. I will do the merge and also update the documentation page. (I plan to remove the numbers from the screenshot, now that there are icons.)

It may still take a few more days until I can make a release which includes Android and macOS.

**Pull request merged**
