### PR TITLE
Remove legacy DXF and OSM support

### PR DESCRIPTION
**Pull request by dg0yt**
Mapper's initial support for DXF and OSM was implemented as addition to the GPX track feature, adding lots of complications and quirks which hinder maintenance and development. I propose to completely remove this legacy code now. There is better support of DXF and OSM through GDAL/OGR. (However, the visual representation is different from the wire-frame GPX track style.)

Who still depends on the old DXF/OSM implementation, enabled by unchecking DXF/OSM on the GDAL/OGR settings page?

### CODE REVIEW

**Comment by yevhenmazur** [comment]
The waypoints description is not visible when GDAL for GPX import is enabled. However I don't think that it is a real blocker for this task. Just FYI.
#### GDAL Disabled
gdal-disabled
#### GDAL Enabled
gdal-enabled

**Comment by dg0yt** [comment]
The idea is to remove the DXF/OSM cruft from the well-accepted existing GPX support ("GDAL disabled"), and then to improve this GPX support (color, line width) instead of the GDAL one.  At the moment it is just too complex.

(Personally, I'm not yet happy with how areas are rendered for OSM via GDAL. I think I' have to reactivate transparency for map colors, or implicitly apply the CRT files and symbol sets. But this is another task.)

**Comment by Symbian9** [comment]
> I think I' have to reactivate transparency for map colors

+1 for transparency reactivating.

Also "map layers" (with opacity), as described in https://github.com/OpenOrienteering/mapper/issues/1121, should be part of this complex task.

**Comment by dg0yt** [comment]
For the record, while Mapper should use the GDAL/OGR import by default since v0.7.92 (d9bca2bece47cf254ae0401f800932b222bec566), I had to learn recently that the legacy DXF and OSM support was used in fresh installations, in contradiction to the settings' checkbox state (#1166). So some users will notice the "new" import only in v0.8.4 or v0.9.0.

**Pull request merged**
