### PR TITLE
Use PROJ 5.1 API

### PR DESCRIPTION
**Pull request by pkturner**
This updates Georeferencing to use the PROJ 5.1 API. I'm initiating this PR to show the status of this work. I've tested it on Linux, and will test more thoroughly including on Android.

The `pj_strerrno` function is replaced with `proj_errno_string`, which was introduced in 5.1.
Search uses the environment's `PROJ_LIB`, as suggested by @dg0yt.

### CODE REVIEW

**Comment by dg0yt** [comment]
Please, base you work on `dev`, not `master`.

I'm not sure how fast we actually want to remove compatibility with PROJ 4.9. Ubuntu 18.04 will be LTS at least until 2020. I don't know when Debian 9 will be replaced.
https://github.com/OpenOrienteering/mapper/wiki/Target-systems#component-version-matrix

**Comment by pkturner** [comment]
I brought the proj-5 branch up-to-date with dev. Now it looks like a mess. Maybe it needs a different branch and/or a new pull request.

Also, checks are failing due to PROJ 5.0's `<proj.h>` not found in Azure.

**Comment by pkturner** [comment]
@dg0yt 
> I'm not sure how fast we actually want to remove compatibility with PROJ 4.9.
Understood. Seeing the component version matrix, you are juggling a great number of dependencies.

**Comment by dg0yt** [comment]
I think you could do the following now:
~~~
git rebase ed39289 --onto dev
~~~

This should cherry-pick your new commits (which are after ed39289) on top of dev.

I'm about to skip PROJ 5 for PROJ 6 in Superbuild if it works for Android, too. However, I'm struggling with the GDAL update to 2.4 which I want to do at the same time. Maybe it is easier to wait a few days.

**Comment by pkturner** [comment]
Changing the PR's base branch in GitHub from `master` to `dev` cleared up the "mess".

**Comment by dg0yt** [comment]
On the PROJ mailing was a [thread about porting to PROJ 6](https://lists.osgeo.org/pipermail/proj/2019-July/008740.html). Some takeaways:
- We need to explicitly handle axis order, at least by axis `proj_normalize_for_visualization`.
- In the long run, we may need to handle (at least for parity with GIS)
  - dynamic datum
  - late binding

**Comment by dg0yt** [comment]
This is now entirely replaced by #1341. Thanks for the excellent starting point. It even helped find bugs in PROJ.

**Pull request closed without merging**
