### PR TITLE
AboutDialog: Update the developer list

### PR DESCRIPTION
**Pull request by lpechacek**
I'm not sure that I'll have enough time to substantially contribute to OO Mapper in the future. Please review the "activity years" for correctness. Thanks!

### CODE REVIEW

**Comment by dg0yt** [comment]
I will wait another two weeks before approving.

**Comment by lpechacek** [comment]
https://github.com/OpenOrienteering/mapper/pull/2272#issuecomment-2499821618 reminded me about this pull request. I agree that humans are on both sides and I want to limits my level of pain by taking a step back from a project where I cannot align my behavior with the group's rules.

I never exercised my rights to merge code into the main branch too much. But if this code change request keeps dangling, I'll make an unilateral decision. As I mentioned, this move is not motivated by anger, but rather by my limited ability to tolerate long-term discomfort.

**Review by dg0yt — COMMENTED** [review]
This is the technical review. 

I never felt comfortable with approving or merging the PR. It is a pity. @lpechacek Feel free to push the merge button yourself if this is what you decided.

**Comment by lpechacek** [comment]
> This is the technical review.

Thanks!

> I never felt comfortable with approving or merging the PR.

Understood. Thanks for your support over the years. I always admired your technical skills, starting with the ability to build Windows binaries in SUSE Build Service. It's been honor for me to contribute to the project.

**Comment by lpechacek** [comment]
> Please continue contributing, independent from any 'About' dialog.

That's my plan. :)

**Pull request merged**
