### PR TITLE
Ukrainian translation review

### PR DESCRIPTION
**Pull request by yevhenmazur**

### CODE REVIEW

**Comment by dg0yt** [comment]
Thanks. Some items remain to be checked and finished, cf. https://hosted.weblate.org/projects/openorienteering/mapper/uk/.

**Comment by yevhenmazur** [comment]
Yes, I know, but I cant approve these items until I don't see them in the interface. If somebody can help me with reproducing of the cases when these messages appears - it is more then welcome.

**Comment by dg0yt** [comment]
Add a source comment in Weblate to ask for clarification.

**Comment by yevhenmazur** [comment]
Thanks, will do so.

**Pull request merged**
