### PR TITLE
Update template lookup

### PR DESCRIPTION
**Pull request by dg0yt**

### CODE REVIEW

**Comment by dg0yt** [comment]
The first commit is the minimal fix for #1325 subissue 2. 

The remaining commits are some more changes around this code. Since this area is not covered well by unit tests, I would be okay with leaving them out if considered too risky for v0.9.

**Comment by dg0yt** [comment]
Couldn't resist to make a few more changes, but I will leave it alone now, if it passes CI.

**Comment by dg0yt** [comment]
I wouldn't say that I have an easy time when I touch any of this legacy code, but obviously I have to do bug fixes.
I don't have a GH issue for refactoring the `Template` mess, but there is a [card in the Refactoring project](https://github.com/OpenOrienteering/mapper/projects/6#card-13986038). Feel free to add some points.

**Comment by lpechacek** [comment]
I can see that I wrote too long comment and my main point drowned in noise. For the sake of future rewrite, I'd be happy to see improved commit message in d5243f0 explaining why template state becomes invalid and why it is safe to switch from `Invalid` to `Unloaded`. If this knowledge does not exist, the commit message should state it too. Thanks!

**Comment by dg0yt** [comment]
The re-assessment is very much appreciated. While reviewing the documentation of what `tryToFindTemplateFile()` does and why, I was able to spot more subtleties in documenation and behaviours, so there is even one more commit now.

**Comment by lpechacek** [comment]
The commit message nicely captures template state semantics. Thanks!

**Pull request merged**
