### PR TITLE
Update lists of developers and contributors

### PR DESCRIPTION
**Pull request by dg0yt**
Who else is missing explicit mention?

### CODE REVIEW

**Comment by pkturner** [comment]
Add me "Scott Turner" as a contributor if I've reached the threshold.

**Comment by dg0yt** [comment]
> Add me "Scott Turner" as a contributor if I've reached the threshold.

Sure! :+1:

**Comment by lpechacek** [comment]
Cross-checking the list with https://www.openhub.net/p/openorienteering-mapper/contributors?query=&time_span=&sort=language I'd propose adding Matthew Pickering, who implemented world file export (92b306187c1b). That would be for C++/C contributions.

**Comment by dg0yt** [comment]
> I'd propose adding Matthew Pickering, who implemented world file export ([92b3061](https://github.com/OpenOrienteering/mapper/commit/92b306187c1bdf942b123db9f1ecaec194cd4e2c)). That would be for C++/C contributions.

@mpickering Any objections against being listed as a contributor in the about dialog?

**Pull request merged**
