### PR TITLE
Merge master into release for v0.9.5

### PR DESCRIPTION
**Pull request by dg0yt**
Postponing `OgrTemplate` progress again, but releasing several months of work on bugfixes, translations, paint-on-template, KMZ export and simple course export.
Help welcome for collecting release notes and preparing the announcement.

After v0.9.5, there will be at least one more release satisfying the same Android, macOS and Windows system requirements. If we manage to do this with nearly the same Qt/PROJ/GDAL requirements, for dependencies provided by major Linux distributions, it will be labeled v0.9.6.

### CODE REVIEW

**Comment by dg0yt** [comment]
Closed issues: https://github.com/OpenOrienteering/mapper/milestone/41?closed=1

**Comment by dg0yt** [comment]
Maybe I should look at #1893 for inclusion in v0.9.5?

**Review by sikmir — APPROVED** [review]

**Comment by dg0yt** [comment]
Thanks @lpechacek. 

I still want to look at #1899. And in the meantime, there was a number of translation updates.

**Review by lpechacek — APPROVED** [review]

**Comment by sikmir** [comment]
> And in the meantime, there was a number of translation updates.

Completed Russian translation.

**Comment by dg0yt** [comment]
The draft release is ready for smoke tests by project members. I will publish it later today if no show stoppers are reported.

**Comment by lpechacek** [comment]
FTR, I've tested Windows x86_64 and Android EABI v7 binaries. All is fine. Thanks!

**Pull request merged**
