### PR TITLE
Add QtCreator *.autosave to .gitignore

### PR DESCRIPTION
**Pull request by sgnewson**

### CODE REVIEW

**Comment by dg0yt** [comment]
Is this an issue with a current version of Qt Creator? I can't remember having seen .autosave files.

**Comment by sgnewson** [comment]
I'm using:
```Qt Creator 4.4.1
Based on Qt 5.9.2 (GCC 5.3.1 20160406 (Red Hat 5.3.1-6), 64 bit)

Built on Oct 4 2017 04:14:10

From revision 6afdb8bdf9```

on Ubuntu 16.04

**Comment by dg0yt** [comment]
Ah, this from the About dialog. I have got the same revision, and the headline says Qt Creator 4.4.1.
I'm still surprised that I don't see .autosave files.

**Comment by dg0yt** [comment]
I verified that Qt Creator creates temporary .autosave files. But these files are removed as soon as the file is saved regularly. That's the reason why I didn't notice them: When I look at git, almost everything is properly saved, because this is done at every build. That's also the reason why I will not merge this pull request:
The presence of a .autosave file indicates that there are unsaved changes. So the presence of a .autosave file strongly indicates that you will miss some of the changes you made. You will loose this hint when we add .autosave to .gitignore.

In addition, most changes are modifications to existing files. The `-u` parameter to `git` easily prevents accidently adding local files which are new or not meant to be committed. I only drop `-u` if I really want to add a new file.

**Comment by sgnewson** [comment]
Makes sense, thanks for the explanation.

**Pull request closed without merging**
