### PR TITLE
Android: Fix baseline view rendering

### PR DESCRIPTION
**Pull request by lpechacek**
Submitting this tiny fix so that it's not lost.

### CODE REVIEW

**Comment by dg0yt** [comment]
The commit message is fine. It is a pity it is somewhat hidden in the Github PR page.

**Comment by dg0yt** [comment]
.. and now this change fixes #1172, at least the bug part of it.

**Comment by dg0yt** [comment]
I took a different approach in 0230da0. I wanted to create a pull request for this and a few more changes, https://github.com/OpenOrienteering/mapper/compare/aef7460...23cdf35, but accidently pushed to `master`. I don't want to reset the protected master, and I will even stage new master builds.
Could you perhaps have a critical look at these changes anyway?

**Comment by lpechacek** [comment]
I'm glad to see multiple issue reports being addressed by the series. AFAICT commit 0230da0e0f12 includes the functionality of my change, obsoleting this PR.

Overall, I don't completely understand the aim for CPU cycle savings on desktop but that's perhaps something to talk about when we meet in person. As expected, the code change alters map appearance when zooming out. For example, in my 1:10 000 test map light brown shades caused by downsized contours, and green shades from undergrowth, disappear at 0.15x zoom level.

In 23cdf355f7e2 ("Don't default to GDAL for GPX") it looks to me like the default is disabled for DXF and not GPX. Am I misreading the code or is it a bug?

Thanks!

**Comment by dg0yt** [comment]
> I don't completely understand the aim for CPU cycle savings on desktop [...]

I'm not to keep on that, but I would very much like to replace the Q_OS_ANDROID hack by a better solution which works for desktop and mobile. As I said, some commits went into `master` too quickly. It will probably become clearer when I manage to place the next pull request.

**Comment by dg0yt** [comment]
> In 23cdf35 ("Don't default to GDAL for GPX") it looks to me like the default is disabled for DXF and not GPX. Am I misreading the code or is it a bug?

This is a bug. This is why we need code reviews ;-)

**Pull request closed without merging**
