### PR TITLE
Cherry pick from #587

### PR DESCRIPTION
**Pull request by Abbe98**
Based on discussion in #587 and cherry picked from there.

Some discussions should be occurring before merge.

### CODE REVIEW

**Comment by dg0yt** [comment]
This is based on an older version of OpenOrienteering_sv.ts, you should ```git merge --no-ff v0.6.1```.

There seem to be a app. 300 more changes in #587. I assume some are left out intentionally. But others seem to add correct punctuation, such as:
~~~
@@ -12,7 +12,7 @@
     <message>
         <location filename="../src/gui/about_dialog.cpp" line="173"/>
         <source>&lt;a %1&gt;All about licenses, copyright notices, conditions and disclaimers.&lt;/a&gt;</source>
-        <translation>&lt;a %1&gt;Allt om licenser, upphovsrätt, villkor och friskrivningar&lt;/a&gt;</translation>
+        <translation>&lt;a %1&gt;Allt om licenser, upphovsrätt, villkor och friskrivningar.&lt;/a&gt;</translation>
     </message>
~~~

The full diff is 2600 lines. I could add it as ZIP, if you don't want to track it in git.

**Comment by Abbe98** [comment]
Will check out the full diff as soon as I can download the branch to my
local client. Another commit should be expected tomorrow.

**Comment by dg0yt** [comment]
@Abbe98 Green light on this one?

**Comment by Zerbembasqwibo** [comment]
In my opionon, there are so many improvement so take whatever version of new translation and it will be better. 

If to change something, the word "Fäst" is better to use "Snappa". But let's do it on next version, maybe to 0.6.3?

**Comment by Abbe98** [comment]
The reason I have not yet done this because lack of time, I have not made
any contributions lately hopefully I will have the time in a few weeks.

2016-05-30 10:32 GMT+02:00 Zerbembasqwibo <notifications@github.com>:

**Pull request merged**
