### PR TITLE
CI: Migrate from PCCR@V1 to ReportGenerator

### PR DESCRIPTION
**Pull request by dl3sdo**
Although the current V1 version of the publish code coverage results task is still available it's recommended to stop using the V1 version and migrate to V2 version.

### CODE REVIEW

**Comment by dl3sdo** [comment]
There seems to be a dispute about migrating to V2:
[New version of Publish Code Coverage Results task](https://devblogs.microsoft.com/devops/new-pccr-task/)
See also:
https://github.com/danielpalme/ReportGenerator/wiki/Integration

**Comment by dg0yt** [comment]
So V2 doesn't offer click-through to the sources.
Do really want to upgrade?
Does https://github.com/danielpalme/ReportGenerator/issues/646#issuecomment-2110990308 provide an alternative?

**Comment by dl3sdo** [comment]
As there is currently nothing that forces us to move to V2 let's give the alternative solution a try, otherwise let's continue with V1.

**Comment by dg0yt** [comment]
I added the ReportGenerator from the AZP marketplace. I couldn't re-run the failed job, but I could start a new run for the same merge commit.

**Comment by dg0yt** [comment]
Seems to work now.
Before: https://dev.azure.com/OpenOrienteering/Mapper/_build/results?buildId=2903&view=codecoverage-tab
After: https://dev.azure.com/OpenOrienteering/Mapper/_build/results?buildId=2907&view=codecoverage-tab

**Comment by dl3sdo** [comment]
> Seems to work now. Before: https://dev.azure.com/OpenOrienteering/Mapper/_build/results?buildId=2903&view=codecoverage-tab After: https://dev.azure.com/OpenOrienteering/Mapper/_build/results?buildId=2907&view=codecoverage-tab

For me it looks rather that one report is V1 and one report is V2 but none of them is Daniel Palme's report.

**Comment by dg0yt** [comment]
AFAIU V1 uses an old version of that ReportGenerator, so similarities are expected.
And you can check the steps run for the coverage pipeline.

In fact, the version is reported in the footer.
Before: ReportGenerator 5.2.2.0
After: ReportGenerator 5.3.8.0

**Comment by dg0yt** [comment]
FTR V2 is https://dev.azure.com/OpenOrienteering/Mapper/_build/results?buildId=2897&view=codecoverage-tab.

**Review by dg0yt — APPROVED** [review]
LGTM.

**Comment by dg0yt** [comment]
Close/Re-open to reset state.

**Comment by dg0yt** [comment]
Thanks.

**Comment by dg0yt** [comment]
This PR was meant to be squashed when merged... I will force-push master.
CC @dl3sdo @lpechacek.

**Pull request merged**
