### PR TITLE
Create map_symbols_lv.ts

### PR DESCRIPTION
**Pull request by XeMoPHOs**
Added translations in Latvian from ISOM2017-2 LV

### CODE REVIEW

**Comment by dg0yt** [comment]
I can to try to merge that once time permits, but the preferred for editing translations is Weblate,
https://hosted.weblate.org/projects/openorienteering/
This does a lot of checks, and it deals with simultaneous edits in a different way.

**Comment by XeMoPHOs** [comment]
OK thank you, did not know that site existed

**Comment by dg0yt** [comment]
To reuse your map symbols translation, you may first click "Start new translation" in the Map Symbols component, which leads to https://hosted.weblate.org/new-lang/openorienteering/map-symbols/, and then choose Latvian

After that, in the Latvian translation of the Map Symbols component, you may choose Files > Upload Translations. 

All these changes will be properly recorded with you being the author.

**Comment by XeMoPHOs** [comment]
Ok

**Comment by dg0yt** [comment]
PR not merged: translation to be uploaded to Weblate.

**Comment by dg0yt** [comment]
@XeMoPHOs Thanks for contributing!

**Pull request closed without merging**
