### PR TITLE
Deprecated methods cleanup (for master)

### PR DESCRIPTION
**Pull request by lpechacek**
Patch set from PR 1681 rebased to current master.

### CODE REVIEW

**Comment by lpechacek** [comment]
@dg0yt if you have no objections, I'll merge the patch set tomorrow evening.

**Comment by dg0yt** [comment]
Thanks, Libor.

`QFontMetrics::horizontalAdvance()` is missing in some versions of Qt that we still support. I didn't want to add `#ifdef`, so I suggest switching to `QFontMetrics::boundingRect()` instead.

**Comment by lpechacek** [comment]
The change makes sense. As the switch to `boundingRect()` effectively replaces the original patch, I'm squashing the two changes into one. In my opinion, it makes no sense to drag the intermediate code state into permanent history. Thanks!

**Comment by dg0yt** [comment]
Saved current `dev` to https://github.com/OpenOrienteering/mapper/tree/dev-20200911, for a few days.
Resetting `dev` to https://github.com/OpenOrienteering/mapper/tree/9a52840598ba9f57baa231d9916d5ec1fbd56729 now.

**Pull request merged**
