### PR TITLE
Update doxygen version to 1.8.13 to fix issue with flex 1.6.X

### PR DESCRIPTION
**Pull request by bagage**
On debian, doxygen is throwing an error, see [upstream bug](https://trac.macports.org/ticket/49881). Bumping doxygen to 1.8.13 fixes the problem.

### CODE REVIEW

**Comment by bagage** [comment]
Bumping this. Required for #517.

**Comment by dg0yt** [comment]
You already have got a patch in F-Droid, and it will be dropped from the master branch here anyway... So why should I merge now? The 0.6.8 PR is meant to give you the chance to have an update without changing things which do work.

**Comment by bagage** [comment]
Yeah, I was doing some cleanup of my existing commits and saw it, but then I cloned superbuild and saw that you already bumped it… I'll try to figure how this work.

**Comment by dg0yt** [comment]
There will be documentation how to use the superbuild but I'm still ironing out some issues.

**Pull request closed without merging**
