### PR TITLE
Release v0.9.3

### PR DESCRIPTION
**Pull request by dg0yt**
Before adding more intrusive template changes, I would like to publish another release.

## Improvements
- Follow border lines when drawing (GH-273)
- Support more geospatial file formats, e.g. from OziExplorer
- Simple support for NMEA position sources on Linux and macOS (e.g. from Bluetooth) (GH-1569)
- Additional space between object control points and selection rectangle (GH-980)
- Clip imported geospatial data to layer boundaries (useful for OSM)

## Corrections
- **Specifying raster image coordinate reference system** (GH-1597)
- Handling of border line as area outline (GH-1602)
- OSM import of roads
- Rare crashes (GH-1578, GH-1600, GH-1608)
- Georeferencing issues, affecting e.g.  EPSG:27700 (OSGB36)

### CODE REVIEW

**Comment by pkturner** [comment]
Regarding Georeferencing state switching ([GH-1593](https://github.com/OpenOrienteering/mapper/pull/1593)), while I regard it as OK to release, I'm continuing to look at it, as it seems I'm beginning to understand "Grivation locked" better.

**Comment by dg0yt** [comment]
> For whatever reason, ‎armeabi-v7a APK from Pipelines refuses to install on my devices. I haven't investigated what's going wrong. 

I guess this happens beause the APK is not yet signed with the release key. You may test with APK from the draft GH release soon.

**Comment by lpechacek** [comment]
> You may test with APK from the draft GH release soon.

Yes, that one works fine.

**Comment by dg0yt** [comment]
Today, #1620 turned up. I wonder if we should have a look if it can be fixed quickly.

**Comment by pkturner** [comment]
#1621 fixes #1620.

**Comment by dg0yt** [comment]
Another fixable issue with the current release candidate: There is a unit test failling with PROJ >= 7.0.0, affecting some Linux distributions, https://github.com/OSGeo/PROJ/issues/1823.

**Pull request merged**
