### PR TITLE
Add Mapper icon source files and readme

### PR DESCRIPTION
**Pull request by guzh**
Ref. #654 

There are two Photoshop files for the icons, one for large sized icons and one for small sizes.
Due to having a few different effects on them the icons where made in PS. The main parts are vector and should be fine to scale up if needed (the large icon is 512px now).

### CODE REVIEW

**Comment by dg0yt** [comment]
Please add the license information to the Readme: "The Photoshop files are licensed CC..." Thanks!

**Comment by guzh** [comment]
Is this okay? :)

**Comment by Symbian9** [comment]
Please, convert those icons to SVG!

**Comment by dg0yt** [comment]
Thanks!

References: https://creativecommons.org/licenses/by/4.0/legalcode, https://creativecommons.org/licenses/by/4.0/

**Pull request merged**
