### PR TITLE
Test NAD83 GPX templates

### PR DESCRIPTION
**Pull request by dg0yt**
Closes GH-1764 (pristine version of this PR).

@pkturner I can add you as a GH project member ("Registered Contributor" group) to acknowledge your input and to allow to add you formally as a reviewer to PRs.

### CODE REVIEW

**Comment by pkturner** [comment]
In `TemplateTrack` I did not see `calculateTemplateBoundingBox` with its function so close to the `getCenter` which I added. It's much nicer the way you reuse that method.

**Comment by pkturner** [comment]
I'd be happy to review some PRs, in the formal way.

**Comment by dg0yt** [comment]
> In `TemplateTrack` I did not see `calculateTemplateBoundingBox` with its function so close to the `getCenter` which I added. It's much nicer the way you reuse that method.

Neither did I when I wrote the `QPicture` trick ;-)

**Comment by dg0yt** [comment]
I'm still editing this series of patches...

**Comment by dg0yt** [comment]
Now the tests also "expect" the failures on PROJ 4.9/GDAL 2 (Ubuntu 18.04).

**Review by pkturner — COMMENTED** [review]
All the changes look good.

I suggest noting alongside the test code or data that the GPX track referenced by the `TemplateTrack NAD83` and `OgrTemplate NAD83` tests is specific to the 2019.73 epoch.

I trust your judgment regarding whether to add an explanation that the NAD83 datum is shifting about 2 cm per year, and that with Mapper built with PROJ 7.1.0 and not specifying an epoch, the track positioning error is about 0.4 m. The test's tolerance is set to 0.125 mm (0.5 m), such that it will be effective for catching regressions.

**Comment by dg0yt** [comment]
Regarding the epoch, we could add `<notes>` to the maps, or `<!--comments-->` to the GPX file. But the GPX file has timestamps anyway. And for having explicit CRS with vector data, will probaly add test cases which will add another element to template configuration, so it will be recorded in another way.

I still wonder whether to keep the separate consistency test. Another alternative is to merge the three tests into a single test (`vectorTemplateTest`) which starts with the GDAL part and is shortcut when the current data is not suitable for templateTrack.

**Pull request merged**
