### PR TITLE
Show line segment length and azimuth while drawing

### PR DESCRIPTION
**Pull request by lpechacek**
The feature can be activated by pressing Ctrl-Space or "Info" button in mobile UI.

References: Issue #398

### CODE REVIEW

**Comment by dg0yt** [comment]
It needs some more work before it becomes really useful with touch input (Android) where we track movements only with finger=button down. However, I need to somewhat cleanup in the tool classes first, any maybe make the state and state changes more explicit, instead of burried in dozens of bools and if/else.

**Comment by lpechacek** [comment]
The code looks much neater now and I like that map rotation is taken into account. I have a comment though.

Info deactivation in finishDrawing() and abortDrawing() was intentional. I use the display only after taking azimuth using [hand-bearing compass](http://www.suunto.com/cs-CZ/Products/Compasses/Suunto-KB-14/Suunto-KB-14360R1/) and draw single straight line segment. I don't need it otherwise, therefore automatic deactivation is convenient for my use case. I'd be happy to hear opinions from more experienced mappers here. @krticka, @ollesmaps, @yevhenmazur, @zlenhart, @akom5524 what is your preference? Should the azimuth display deactivate upon finishing the line or should it remain active until you click the button again?

Regarding the field experience, I'm happy with the way the feature works on Nvidia Shield tablet with stylus. The only downside I see now is that the mobile UI button does not reflect the azimuth display state. That's, however, the same as with the Dash button, which retains its look regardless the dash point status.

**Comment by dg0yt** [comment]
> Info deactivation in finishDrawing() and abortDrawing() was intentional. 

I was expecting something like that. Is it disturbing to leave it turned on (until explicitly deactivated)?

> The only downside I see now is that the mobile UI button does not reflect the azimuth display state. That's, however, the same as with the Dash button, which retains its look regardless the dash point status.

That's a short coming of the KeyButtonBar as it is now. Maybe to be fixed now..

**Comment by lpechacek** [comment]
> I was expecting something like that. Is it disturbing to leave it turned on (until explicitly deactivated)?

I need to test the current version in the field before answering your question. But as adding the automatic deactivation is trivial, the feature can be made configurable and there was no immediate feedback from other users, I'm for merging the code as it is now.

**Comment by dg0yt** [comment]
Okay.

**Comment by dg0yt** [comment]
Still need to update the azimuth info when pressing Backspace on a curved segment.

**Comment by krticka** [comment]
On desktop seems to work OK, thank you!
@lpechacek Is there latest unstable build for android available? I will test it in terrain.

**Comment by dg0yt** [comment]
I hope I can provide a new 0.8.0 beta release in the next days.

**Comment by lpechacek** [comment]
> @lpechacek Is there latest unstable build for android available? I will test it in terrain.

I'm using [http://liborpechacek.wz.cz/oomapper/mapper-issue398-g0721f412f09c.apk](http://liborpechacek.wz.cz/oomapper/mapper-issue398-g0721f412f09c.apk) for my field work.

**Comment by akom5224** [comment]
Hello,

thanks from me as well for implementing this tool!

Just a brief reply to the question on automatic deactivation of the tool 
(even though I would not call myself as "more experienced mapper" ;-)). 
I think that both (automatic deactivation or not) are useful in 
different situations and the preference will highly depend on a user. My 
(relatively mild) preference is NOT to deactivate it automatically. The 
reason is that when I want to draw azimuth lines then often I need to 
draw more of them (e.g., to fix a point object from two different 
positions) and automatic deactivation would be annoying in such 
situations. Once I am done with azimuth lines, I can switch it off 
manually and find this more handy than to switch it on for each single line.

Best wishes,
Arnost (akom5224)


Libor Pecháček schreef op 10/31/2017 om 08:41 PM:

**Comment by lpechacek** [comment]
Thanks for describing your use case, Arnošt!

A brief update from my side. I spent Sunday morning in the field, with Mapper built from commit 0721f41, and found current behavior mostly OK. The only annoying part was that I didn't see whether the azimuth display is on or off before starting a line. That part is resolved in commit 333fd04 and I'm going to test the updated version.

**Comment by yevhenmazur** [comment]
Could you please provide the actual build? I want to join to the testing of this feature.

**Comment by lpechacek** [comment]
Just build today's master (214afa6abc18) for my testing: http://liborpechacek.wz.cz/oomapper/mapper-issue398-g214afa6abc18.apk. HTH

**Comment by lpechacek** [comment]
@krticka, @yevhenmazur, go ahead and grab the official build at https://github.com/OpenOrienteering/mapper/releases/tag/v0.7.92. I'm going to delete the development builds soon.

**Comment by krticka** [comment]
Works OK for me!
Probably info about angle can be useful also when you want to repair direction/rotation of existing object. Now there is no option how to find it as measure tool shows only length for line objects, perimeter and area for polygon object and nothing for point object.

**Comment by lpechacek** [comment]
I'm also missing the azimuth display in edit mode. Unfortunately, the code structure for path editor is very different from the draw path tool so I had no good idea how to stick the azimuth display into it.

**Comment by dg0yt** [comment]
Some tools are really ugly and difficult to extend. This also blocks better touch input handling. I started porting DrawPathTool to use explicit states and input/action handling (state machine) as part of merging the azimuth info contribution, but I decided to hold the more challenging parts back for integration after v0.8.0.

**Comment by ollesmaps** [comment]
Here I come for testing. I can't find the Info button that shall activate it though (Android). Thanks for hint.

**Comment by krticka** [comment]
Are you using beta? [https://github.com/OpenOrienteering/mapper/releases/tag/v0.7.92](https://github.com/OpenOrienteering/mapper/releases/tag/v0.7.92)

**Comment by ollesmaps** [comment]
Yes

**Comment by akom5224** [comment]
Info button appears on bottom of the map if you (a) choose a line object 
and (b) choose a straight line mode of drawing. It seems that it then 
remains activated even for all subsequent line objects (till deactivated).


Aleš Hejna schreef op 11/30/2017 om 12:46 PM:

**Comment by ollesmaps** [comment]
Great enhancement! Thank you!
It best works with a special help symbol (thin purple line?) that you stick in your location and draw there and back, there and back till you receive your angle acquired by compass.  Than copy the angle with the right symbol.
If it worked in Edit mode this "thereandbacking" would be unneeded. 

I have not used it during fieldwork though. Will report later.

**Comment by ollesmaps** [comment]
Now I see the numbers get activated also when drawing dragging (thanks @zlenhart for pointing it out). Brilliant!

**Comment by Zerbembasqwibo** [comment]
Yes close it.

**Pull request merged**
