### PR TITLE
Finalize release v0.9.0

### PR DESCRIPTION
**Pull request by dg0yt**
Key changes since 0.8.4

- Significantly improved OCD format support, including export up to version 12, georeferencing and symbol icons.
- ISOM 2017-2 symbol set.
- GeoTIFF support
- Geospatial vector data export.
- Android: adjustable tool button size, 64-bit support, standy/background mode improvements.
- "Touch mode" including GPS support also for Windows/macOS/Linux.
  Note that access to the Windows location requires .NET Framework 4 and Powershell 2 (included in Windows 10).
- A significant modernization of 3rd-party components (Qt 5.12, PROJ 6, GDAL 3).

### CODE REVIEW

**Comment by dg0yt** [comment]
Proposed release procedure:
1. Merge this PR.
2. Validate CI results.
3. Create draft GH release from CI.
4. Leave 24h for project members to test the draft release binaries (macOS, Windows, Android).
5. Publish and announce the release.
6. Bump version to 0.9.1 in master.
6. Merge master into dev.
7. Bump version to 1.0.0 in dev.

**Comment by lpechacek** [comment]
On the user visible changes, there is the "corner point click-in" editing mode and perhaps one more, where I volunteered to draft the release notes entry. Will review the list tomorrow morning.

**Comment by lpechacek** [comment]
I suggest pointing out user interface changes in a separate RN section:
* Adjustable action button size in mobile UI (already mentioned in the first comment)
* Ctrl-A no longer selects hidden and protected symbols (73ac0dc)
* Scale tool can now resize multiple objects in place (7d32bca5)
* Corner points on curves can be edited more easily (822a912)

**Comment by dg0yt** [comment]
Thanks for feedback. I edited the list of changes, but I left out Ctrl-A bug fix.

**Comment by dg0yt** [comment]
CI went smoothly without warnings or errors, and a Github release draft was created, with binaries for testing.
Planned publishing app. Tue Oct 23, 9am CEST.

**Comment by lpechacek** [comment]
> Leave 24h for project members to test the draft release binaries (macOS, Windows, Android).

I've quickly tested arm64-v8a.apk on Android Q and 64bit Windows version on Windows 10. Both looked good.

**Comment by dg0yt** [comment]
macOS and Windows x64 ZIP seem allright.

**Comment by dg0yt** [comment]
> Planned publishing app. Tue Oct 23, 9am CEST. 

Hm, this was meant to say Tue Oct *22*. I will publish the release tonight.

**Comment by lpechacek** [comment]
FWIW, the plan was clear for me - 24h for review, i.e. from Monday to Tuesday, publishing time 9am. I didn't even notice the typo in date. That said, I'm for immediate release so that European and Asian time zones can enjoy the Mapper refresh today.

**Comment by sikmir** [comment]
2019?
https://github.com/OpenOrienteering/mapper/blob/608eb9ee364aaf6799acdf23978670c100ad1c70/src/gui/about_dialog.cpp#L167

**Comment by dg0yt** [comment]
Thanks Nikolay. Building the Linux packages revealed a few more things to be updated. But first I have to update the CI setup for Azure Pipeplines changes...

**Pull request merged**
