### PR TITLE
Misc. typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.ts,./3rd-party -L ba,childs,iff,nd,uint`

### CODE REVIEW

**Comment by dg0yt** [comment]
Thanks a lot. I'm not sure how and when to merge this, as it touches different types of content, some of it generated (examples and symbol sets variants), some of it maintained in a separate repository (manual). There is also a number of pending larger pull requests for dev. (Anyway, dev is the right target here.) So I probably need to split this up. 
Is codespell something which is usable in git commit-hooks?

**Comment by dg0yt** [comment]
Now also merged to the online manual. Thanks!

**Comment by luzpaz** [comment]
> Is codespell something which is usable in git commit-hooks?

@dg0yt sorry for not responding to your question
I'm not sure. There is an issue discussing how to integrate codespell as a CI step: 
checkout: https://github.com/codespell-project/codespell/issues/139 maybe you can get ideas on how to do it from there? I haven't used `git commit-hooks`. Care to share how you use it?

**Comment by dg0yt** [comment]
I can't say much about commit hooks. For CI (Microsoft Azure Pipelines), I added a new job which just runs `codespell` and turns the findings into proper warnings:
https://github.com/OpenOrienteering/mapper/pull/1221/commits/65bf23687ebf34a1ddd0537505a501cc8e951d64

The result before fixing the typos is here:
https://dev.azure.com/OpenOrienteering/Mapper/_build/results?buildId=198&view=results

Note that the column number is missing already in codespell output.

**Pull request merged**
