### PR TITLE
Update OpenOrienteering_sv.ts

### PR DESCRIPTION
**Pull request by Zerbembasqwibo**
Made adjustments from lne 1 to 773.

Line 716 , origin(eng) = origo(sve)?

    <message>
        <location filename="../src/gui/configure_grid_dialog.cpp" line="221"/>
        <source>Origin at: %1</source>
        <translation>Ursprung vid: %1</translation>
    </message>
    <message>
        <location filename="../src/gui/configure_grid_dialog.cpp" line="223"/>
        <source>paper coordinates origin</source>
        <translation>pappers koordinaters ursprung</translation>
    </message>
    <message>
        <location filename="../src/gui/configure_grid_dialog.cpp" line="225"/>
        <source>projected coordinates origin</source>
        <translation>projekterade koordinaters ursprung</translation>

### CODE REVIEW

**Comment by dg0yt** [comment]
You can contribute this way (i.e. changing files), and you can even update the pull request. I didn't test it, but probably you just need to push new changes to ```Zerbembasqwibo:patch-1```.

**Comment by dg0yt** [comment]
I can just check the abstract syntax (dots and colons etc.). Maybe @Abbe98 wants to comment on the language.

**Comment by Zerbembasqwibo** [comment]
Yes it would be good. I have done some more now and there are at least 10
words I can't understand how to translate, must look at those together with
someone else.

Regards,
//Sven

2016-01-18 21:34 GMT+01:00 Kai Pastor <notifications@github.com>:

> I can just check the abstract syntax (dots and colons etc.). Maybe @Abbe98
> <https://github.com/Abbe98> wants to comment on the language.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenOrienteering/mapper/pull/587#issuecomment-172646894>
> .
>



-- 

Skickat från min Xpensius Mulitfrekvensus supercoola telefon som
sprider massa dryg reklam till alla jag e-postar.

**Comment by Zerbembasqwibo** [comment]
So I made the rest too.... I don't know what to do now, so @Abbe98 can check, I have several questions, partly in the code, partly in the comment. At least I found lots of things to improve. :)

**Comment by Abbe98** [comment]
Reviewing it later tonight!

**Comment by Abbe98** [comment]
I could not comment on lines in the main commit as the diff was to large, but the small one seams to be all good. 

Make sure you know where all the translations is used in the actual application so it makes sense "in action", also make sure that it's consistent. I know that translations such as "dekorfärg"/"ankare" can be a bit weird but as long as it's consistent it isn't a issue(I saw your note about "ankare" not being consistent btw).

**Comment by Zerbembasqwibo** [comment]
How to find where it is used in the program? Some I couldnt find/have never
seen.

I made two versions of the file, is that a problem? They should be merged.

In swedish about how to get correct translations:
Men för att ta det på svenska, det är väl ca 30 uttryck som jag är osäker
på som borde lyftas/jämföras med OCAD. Ska man göra en tråd på
orienterare.nu om det? Eller har du kollat alla nu? Jag förstod inte det du
skrev.

Sven

2016-01-19 17:11 GMT+01:00 Albin Larsson <notifications@github.com>:

> I could not comment on lines in the main commit as the diff was to large,
> but the small one seams to be all good.
>
> Make sure you know where all the translations is used in the actual
> application so it makes sense "in action", also make sure that it's
> consistent. I know that translations such as "dekorfärg"/"ankare" can be a
> bit weird but as long as it's consistent it isn't a issue(I saw your note
> about "ankare" not being consistent btw).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenOrienteering/mapper/pull/587#issuecomment-172901815>
> .
>



-- 

Skickat från min Xpensius Mulitfrekvensus supercoola telefon som
sprider massa dryg reklam till alla jag e-postar.

**Comment by Abbe98** [comment]
For more information about testing a translation see https://github.com/OpenOrienteering/mapper/wiki/Translation

Jag är inte den person som ursprungligen översatte programmet. Så länge som uttrycken är de samma hela vägen igenom och inte kan förväxlas så är namngiven inget större problem. Om det är något vanligt förekommande uttryck som du tror borde helt byta namn så bör det diskuteras först.

**Comment by dg0yt** [comment]
Is this ready to merge or still work in progress?

> How to find where it is used in the program? Some I couldnt find/have never seen.

I could help you if you ask.

**Comment by Zerbembasqwibo** [comment]
I have done nothing more, did that other swedish user do or not, I don't
know. I guess my translation is somewhat better than the original one, but
nevertheless there are some terms that need some more energy to be
translated better.

I suggest to merge the two files I made, but I dont know/understand how to
do it on github.

I can ask you for some terms but I need to search for them, have not that
time just now today.

2016-02-06 1:09 GMT+01:00 Kai Pastor <notifications@github.com>:

> Is this ready to merge or still work in progress?
>
> How to find where it is used in the program? Some I couldnt find/have
> never seen.
>
> I could help you if you ask.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenOrienteering/mapper/pull/587#issuecomment-180631055>
> .
>



-- 

Skickat från min Xpensius Mulitfrekvensus supercoola telefon som
sprider massa dryg reklam till alla jag e-postar.

**Comment by Zerbembasqwibo** [comment]
Some questions on where in the program these parts are used. I think if I can look at these things the two files I prioduced can be merged (I don't know how) and than be included in the real code.

Row numbers refers to approx position in this file: 
https://github.com/Zerbembasqwibo/mapper/blob/5aa39a15eb3678ecff18d57c8df1411cc656074b/translations/OpenOrienteering_sv.ts

Regards,



1.
<location filename="../src/symbol_area.cpp" line="773"/>
          <source>Line fill</source>
 -        <translation>Linjefyllningar</translation>

Does it mean the color of a line, or something that is between two lines?

2.
         <location filename="../src/symbol_combined.cpp" line="408"/>
          <source>- Private area symbol -</source>
 -        <translation>- Privat yt symbol -</translation>

Private as in personal? 

3. 
         <location filename="../src/gui/configure_grid_dialog.cpp" line="68"/>
          <source>Additional rotation (counter-clockwise):</source>
 -        <translation>Ytteligare rotation (motsols)</translation>

Where is it used? Must see the context.

4.
        <location filename="../src/tool_draw_path.cpp" line="91"/>
        <source>Dash</source>
        <comment>Drawing dash points</comment>
        <translation>Streckad</translation>

Is it the verb Drawing, like the program/operator is doing something?

5.
        <location filename="../src/tool_draw_rectangle.cpp" line="81"/>
        <source>Dash</source>
        <comment>Drawing dash points</comment>

Is it the verb Drawing, like the program/operator is doing something?


6. (row 1782)
    <message>
        <source>Scale only</source>
        <translation type="vanished">Bara skala</translation>

Scale is verb or noun?

7. (row 1947)
        <location filename="../src/gui/georeferencing_dialog.cpp" line="93"/>
        <source>Map coordinate reference system</source>
        <translation>Kartans referenskoordinatsystem</translation>

Is it same as coordinate system, or is coordinate reference system something else than just coordinate system?

8. 
Misprint in English? 
Line 3905 Should be "        <source>Select a point symbol to be able to use this tool.</source>" -> "to activate this tool" ?

9. (row 4846) (also 4943)
<location filename="../src/file_format_ocad8.cpp" line="1589"/>
        <source>Registration black is exported as a regular color.</source>
        <translatorcomment>Avses passningsmärkets färg?</translatorcomment>
        <translation>Registrerings svart exporteras som en vanlig färg.</translati

Is it the color of the registration mark?

10.
Row 5727
<message>
        <location filename="../src/gui/print_widget.cpp" line="1044"/>
        <source>Print Preview Progress</source>
        <translation>Utskrifts Förhandsvisnings Framsteg</translation>

To print the progress, or how much progress the printing process has? Where is the context?

11. 
(row 6190)
<message>
        <source>Unable to export template: file type of &quot;%1&quot; is not supported yet</source>
        <translation type="obsolete">Kunde inte exportera mall: filtypen &quot;%1&quot; stöds inte än</translation>
Template as in background? Context, where?

12. (row 6408)
<message>
        <location filename="../src/symbol_dialog_replace.cpp" line="55"/>
        <source>Symbol mapping:</source>
        <translation>Symbolmatchning:</translation>
Context? Mapping as in find a friend, not cartographing.

13.
(row 6499)
        <location filename="../src/map_dialog_rotate.cpp" line="52"/>
        <source>Georeferencing reference point</source>
        <comment>Rotation center point</comment>
        <translation>Georefererat rotationscentrum</translation>

Noun/verb, unclear to me. Context needed.

14.
(row 6534)
    <message>
        <location filename="../src/map_dialog_rotate.cpp" line="72"/>
        <source>Adjust georeferencing reference point</source>
        <translation>Justera georeferenspunkt.</translation>
How is that point defined? 

15. 
(Row 6540)
    <message>
        <location filename="../src/map_dialog_rotate.cpp" line="79"/>
        <source>Adjust georeferencing declination</source>
        <translation>Justera georeferensens missvisning</translation>
Context needed to understand if it is a command to the program to execute, or if user should add some values.

16. 
(row 6725)
    <message>
        <location filename="../src/gui/select_crs_dialog.cpp" line="54"/>
        <source>Select coordinate reference system</source>
        <translation>Välj koordinatsystem</translation>

Context needed.

17. 
(row 7047)
    <message>
        <location filename="../src/gui/widgets/symbol_render_widget.cpp" line="1150"/>
        <source>Add all objects with this symbol to selection</source>
        <translation>Välj alla objekt med denna symbol</translation>
Need context. To choose all symbols, or to choose all object of that kind of symbol to add to selected objects?

18.
(row 6625)
        <location filename="../src/map_dialog_scale.cpp" line="48"/>
        <source>Map coordinate system origin</source>
        <comment>Scaling center point</comment>
        <translation>Kartkoordinats centrum</translation>

"Scaling" = verb or "Scaling center point" is a noun? Context needed.

19.
(row 7112)
        <location filename="../src/symbol_setting_dialog.cpp" line="114"/>
        <source>bounding box on origin</source>
        <translation>begränsningsruta på utgångspunkten</translation>
Origin = "origo" or "where something starts"? Several places in the code.

20. 
        <location filename="../src/gui/widgets/measure_widget.cpp" line="99"/>
        <source>Boundary length:</source>
        <translatorcomment>Osäker på denna.</translatorcomment>
Need context.

21.
(row 7263)
    <message>
        <location filename="../src/template_adjust.cpp" line="572"/>
        <source>&lt;b&gt;Click&lt;/b&gt;: Set the template position of the pass point. </source>
        <translation>&lt;b&gt;Klicka&lt;/b&gt;: Placera bakgrundsbildpositionen för kalibreringspunkten. </translation>
                <translatorcomment>Blev detta rätt?</translatorcomment>

Need context

22.
(row 5727)
    <message>
        <location filename="../src/gui/print_widget.cpp" line="1044"/>
        <source>Print Preview Progress</source>
        <translation>Utskrifts Förhandsvisnings Framsteg</translation>
        <translatorcomment>Vad avses?</translatorcomment>
Need context.

**Comment by Zerbembasqwibo** [comment]
Anyone who can help me with
1) how to merge these two files I created?
2) help me find where in the program my 22 questions above are situated
3) suggestions to improve the tranlations?

**Comment by Abbe98** [comment]
I intend to investigate this tomorrow afternoon(train trip), have been having a hard time finding the time to catch up...

1.  If both are committed to Git, they seams to have been merged, if not you has to manually edit the files.
2. investigating tomorrow.
3. ^^

@Zerbembasqwibo it's likely that I based on your questions and thoughts will make a new pull request, that will cause a conflict with this pull request.

**Comment by Zerbembasqwibo** [comment]
Great! :)

2016-02-21 21:00 GMT+01:00 Albin Larsson <notifications@github.com>:

> I intend to investigate this tomorrow afternoon(train trip), have been
> having a hard time finding the time to catch up...
>
>    1. If both are committed to Git, they seams to have been merged, if
>    not you has to manually edit the files.
>    2. investigating tomorrow.
>    3. ^^
>
> @Zerbembasqwibo <https://github.com/Zerbembasqwibo> it's likely that I
> based on your questions and thoughts will make a new pull request, that
> will cause a conflict with this pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenOrienteering/mapper/pull/587#issuecomment-186899171>
> .
>



-- 

Skickat från min Xpensius Mulitfrekvensus supercoola telefon som
sprider massa dryg reklam till alla jag e-postar.

**Comment by dg0yt** [comment]
ad 1) "Line fill" is a type of area symbol fill pattern:
line-fill

**Comment by dg0yt** [comment]
ad 2) "- Private area symbol -", as "- Private line symbol -", is a sub-symbol of a combined symbol which is local (or "private") to this particular combined symbol, i.e. it is neither offered as a regular symbol for drawing, nor can it be used in another combined symbol.
private-line-symbol

**Comment by dg0yt** [comment]
Ad 3) Cf. http://www.openorienteering.org/mapper-manual/pages/grid.html

**Comment by Abbe98** [comment]
I have opened a new pull request based on this one. I have addressed most of your thoughts and made some other fixes. 

On the topic of context it's something that the Mapper UI provides. For example the print-progress dialog have a progress bar providing actual context. Context isn't created in the translations.

Coordinate system is different from coordinate reference system(CRS), yes (http://www.crs-geo.eu/nn_124224/crseu/EN/CRS__Overview/definition-crs__node.html?__nnn=true).

**Comment by dg0yt** [comment]
@Zerbembasqwibo: 
- You really need to use either Qt Linguist, or at least some XML editor. 
- The git commit messages are much more verbose than what I want to merge to our source code. 

However, I'm confident your contribution will make its way into #604. Your comments may change the way how I comment the to-be-translated parts in the source code. (I can add extra comments for translators.) Anyway, use Qt Linguist for a good experience.

**Comment by Zerbembasqwibo** [comment]
OK, I see. I am very much beginner in this but I'll do my very best...

I think I'll ask some programming friend to explain what to do. And what
Albin did, I don't get it but don't waste time on me - fix a bug instead! :)

2016-02-22 18:16 GMT+01:00 Kai Pastor <notifications@github.com>:

> @Zerbembasqwibo <https://github.com/Zerbembasqwibo>:
>
>    - You really need to use either Qt Linguist, or at least some XML
>    editor.
>    - The git commit messages are much more verbose than what I want to
>    merge to our source code.
>
> However, I'm confident your contribution will make its way into #604
> <https://github.com/OpenOrienteering/mapper/pull/604>. Your comments may
> change the way how I comment the to-be-translated parts in the source code.
> (I can add extra comments for translators.) Anyway, use Qt Linguist for a
> good experience.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenOrienteering/mapper/pull/587#issuecomment-187274699>
> .
>



-- 

Skickat från min Xpensius Mulitfrekvensus supercoola telefon som
sprider massa dryg reklam till alla jag e-postar.

**Comment by Zerbembasqwibo** [comment]
Hi again, I can write but I don't understand what is missing in the "code" to merge this improved translation. Abbe98 seems to not done it either. 

Is it anyone that can help? Now there are two bransches, at least, of this translation.

**Comment by dg0yt** [comment]
Today I merged #604. This leaves out any additions from this pull requests.

I hope we get a translation project on Weblate (#605) so you can work on this more easily again.

**Comment by Zerbembasqwibo** [comment]
Great. It's so annoying to read "Backgrundsbilder" (spells
"bakgrundsbilder") every time I use OOM... :)

2016-06-16 7:51 GMT+02:00 Kai Pastor <notifications@github.com>:

> Today I merged #604 <https://github.com/OpenOrienteering/mapper/pull/604>.
> This leaves out any additions from this pull requests.
>
> I hope we get a translation project on Weblate (#605
> <https://github.com/OpenOrienteering/mapper/issues/605>) so you can work
> on this more easily again.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenOrienteering/mapper/pull/587#issuecomment-226394169>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APa4DziLs26inWOmcgtMUiW6v5qY2aH9ks5qMORSgaJpZM4HHJsF>
> .
>



-- 

Skickat från min Xpensius Mulitfrekvensus supercoola telefon som
sprider massa dryg reklam till alla jag e-postar.

**Comment by dg0yt** [comment]
Unstable builds are updated now.

**Comment by Zerbembasqwibo** [comment]
Hi, nice my work start to be used! But I am still very confused. I found the unstable version, and still there are old translations that I suggested to change, left unchanged. 

Why was not all suggestions used?

Anyway, if I want to change it again: **what file to work in**? Link would be best. Sorry am I not god enough programmer to understand, but I really can improve the Swedish translation.

I realised some words must be changed again, now when I see it "live".

I am really  greatful for all work you put in this project!!

**Comment by Zerbembasqwibo** [comment]
Oops, closing this was a mistake. Reopened it.

**Comment by dg0yt** [comment]
The best thing (without using git) is to download the repository's ZIP archive from the master branch (https://github.com/OpenOrienteering/mapper/archive/master.zip), extract, and open translations/OpenOrienteering_sv.ts in Qt Linguist.

I add Linguist to our unstable Windows package (aka "development snapshot") now. I will publish this later tonight.

**Comment by dg0yt** [comment]
You can now edit the translation online on https://hosted.weblate.org/projects/openorienteering/mapper/sv/. Just register/login with your Github account. 

I close this old request now, without merging.

**Comment by Zerbembasqwibo** [comment]
Very nice tool. Checked 200 first now. Fixed things I easily could fix.

2016-07-21 8:41 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by Abbe98** [comment]
Amazing @Zerbembasqwibo, happy to see that there is now the web interface for translations.

I'm sorry for not getting the time to get your changes merged earlier.

**Comment by Zerbembasqwibo** [comment]
I worked through all 1321 strings now. I have adjusted all I saw was
wrong/strange/bad, but still there are many which needs revision. I marked
them and I added comments to other translators. I cannot do any more to
this now, but the file is anyway useful and with less errors than before.

2016-07-21 12:10 GMT+02:00 Albin Larsson <notifications@github.com>:

**Comment by dg0yt** [comment]
Many thanks. I'm about to prepare v0.6.4 tonight, and I will include what is finished. Some remarks:

- Translation which are marked "Needs review" on Weblate are marked "unfinished" in the export. This means they will not be used in the releases! In some cases, you might have also used the "Suggestion" field.
- Comments in your local language always belong under the scope "Translation comment" (limited to this particular language). The scope "Source comment" is read by developers and all translators (in all languages), so this is for clarification issues and requests for change. Consequently, this must be in English.

Don't worry, I had to learn this, too. I already started to update the translation instruction in our wiki.

**Comment by Zerbembasqwibo** [comment]
I'll try to fix it immidiately. I skip "needs review" and use just
"Translation comment" instead.

2016-08-01 19:07 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by Zerbembasqwibo** [comment]
But right now the Weblate is extremely slow. :(

2016-08-01 19:11 GMT+02:00 Sven Lundbäck <sven.lundback@gmail.com>:

**Comment by Zerbembasqwibo** [comment]
Done. I hope now it will fit into 0.6.4! :)

2016-08-01 19:22 GMT+02:00 Sven Lundbäck <sven.lundback@gmail.com>:

**Pull request closed without merging**
