### PR TITLE
CoVe - Contour line vectorization

### PR DESCRIPTION
**Pull request by lpechacek**
While CoVe was developed for vectorization of contour lines from scanned paper maps, it can essentially be leveraged for any line object in any bitmap. Last time it saved me time on vectorization of intricate logos from bitmaps.

The pull request is split into two parts - the CoVe code itself and Mapper integration. The code contains quite a few translatable strings. Czech translations are at https://github.com/lpechacek/cove/tree/master/app/translations and I welcome suggestions about how to integrate them into the Mapper l10n system.

Please note that potrace by Peter Selinger is included in CoVe code.

### CODE REVIEW

**Comment by dg0yt** [comment]
With regard to the next master release, I tend to merge this quickly, and to work on small changes afterwards. This would include reviewing/handling translations.
After the merge, I would make some changes via PRs here, adding you as a reviewer for non-trivial modifications.

If this procedure is okay for you, the PR can be regarded as approved.

**Comment by lpechacek** [comment]
No objection from me. I'll merge the patches now. Thanks!

**Comment by mpickering** [comment]
Is there some documentation somewhere for this feature?

**Comment by lpechacek** [comment]
Yes. There is a "quick how-to" at https://github.com/OpenOrienteering/mapper/issues/833#issuecomment-416913762 . More extensive documentation in the Czech language is in http://liborpechacek.wz.cz/programming/cove/BP-LiborPechacek.pdf, pages 36 and on. Google translate should be able to make a decent translation of texts copied from the PDF.

Volunteers for compiling a Mapper manual page are warmly welcome.

**Comment by mpickering** [comment]
@lpechacek I made a video demonstrating how to use the vectoriser as "documentation" https://www.youtube.com/watch?v=iIumQdg7qxY

**Comment by lpechacek** [comment]
@mpickering, many thanks for creating the video! That's indeed a good first step to have the new feature documented. :)
Ad dashed form lines in the example, it is possible to turn them into continuous lines too. There is _Longest gap_ parameter in _Vectorization options_ dialog telling the vectorization engine how large gap (in pixels) it should try to bridge. Increasing the value will make dashed line segments merge into continuous lines. However, by default, the vectorizer is set to perform joins where there are only two ends available. Increasing the longest gap value will give the vectorizer more possibilities to join line ends. It is desirable to uncheck _Perform simple joins only_ then and let the software make decisions about which line ends belong to each other. Another downside of increasing the maximum gap size is an increased number of wrong connections. Feel free to play with the settings. Suggestions for improvements are welcome.

**Pull request merged**
