### PR TITLE
Fix concurrent image processing

### PR DESCRIPTION
**Pull request by dg0yt**
Assumed to (help) resolve GH-1503.
However, not yet tested in an environment which reproduces the issue.

### CODE REVIEW

**Comment by lpechacek** [comment]
FWIW, images are generated correctly now in my test case. I'll dive into the patch set later on. Thanks!

**Comment by dg0yt** [comment]
I'm still working on extending unit test coverage around my QImage handling, it is quite telling...

**Comment by dg0yt** [comment]
So in the end, I learned that I don't need InplaceImage. It was just hiding the failure to implement perfect forwarding correctly. OTOH there was a problem with the const char*-taking constructor of QImage when used with index image formats which require a color table. I will create a Qt bug report.

**Comment by dg0yt** [comment]
Reported https://bugreports.qt.io/browse/QTBUG-81674

**Comment by dg0yt** [comment]
I must admit that I just see GH-1503 happening again, although not always, when switching between Colors and Thinning tab. But not a single crash... Maybe it is still some unexpected detaching in QImage.

**Comment by dg0yt** [comment]
> Maybe it is still some unexpected detaching in QImage.

Indeed, there is occassional detaching during processing. But why only sometimes?

**Comment by dg0yt** [comment]
So, finally making sure that the worker functions get a target QImage which is not implicitly shared with another instance, by creating this target QImage in the worker thread.

@lpechacek Ready for review, to be merged for the next master snapshot.

**Comment by dg0yt** [comment]
... took out unrelated changes (unused slots, BW image history) - will move them to the refactoring PR.
Anyway, I will probably merge this soon, approved or not. I face #1503 w/o this PR, but not with this PR.

**Comment by lpechacek** [comment]
Thanks for the improvements, Kai! I'll review the patches tomorrow morning.

**Pull request merged**
