### PR TITLE
Training course symbol set

### PR DESCRIPTION
**Pull request by Abbe98**
A set with custom course symbols useful when making complex training courses.

For review before, edits to this pull request is likely. 

screenshot

### CODE REVIEW

**Comment by dg0yt** [comment]
- The symbol numbers are above 999.9. Do you know if this is compatible with OCD 8 or 11? Otherwise I would suggest using numbers between 900.0 and 999.9.
- The symbols need to get a description.
- Can the symbols be used in 1:10000 (1:5000, 1:4000) without change in dimensions?

**Comment by Abbe98** [comment]
- something I didn't think of!
- work in progress
- no, I believe such a symbol set is most relevant for 15000 and 10000 but
maybe it should be available for sprint scales too.

**Comment by Abbe98** [comment]
Tested the symbols in OCAD(11), and added basic descriptions.

**Comment by Abbe98** [comment]
@dg0yt on the topic of dimensions, I'm targeting only 10000 & 15000 at this time. How is the ISOM symbolset currently dealing with generating the 10000 `.omap` file?

As far as I can see this would cause no issues with dimensions between the 15000 & 10000 `.omap`.

**Comment by Symbian9** [comment]
This issue in some way related
https://github.com/OpenOrienteering/mapper/issues/664

**Comment by dg0yt** [comment]
Any update on this one? There are now also control descriptions (#718) although not merge yet.

**Comment by Abbe98** [comment]
I have not done any work on sprint scales,  for 10000/15000 where I think it most relevant. Also as mentioned above it's compatible with OCAD. It could be merged as it's?



I would personally opposite a merge of #718.

**Comment by dg0yt** [comment]
If there are substantial arguments against #718, bring it up there.

**Comment by dg0yt** [comment]
Do you want to update or elaborate this PR? Otherwise I'd rather close it.

**Pull request closed without merging**
