### PR TITLE
Update OpenOrienteering_zh_CN.ts

### PR DESCRIPTION
**Pull request by xianchb**
Chinese translations

### CODE REVIEW

**Comment by lpechacek** [comment]
Reading through https://github.com/OpenOrienteering/mapper/wiki/Translation#information-for-translators, I would say that the preferred way of contributing translations is through Weblate. What makes you contribute the Chinese translations through a GitHub pull request, please?

**Comment by xianchb** [comment]
> Reading through https://github.com/OpenOrienteering/mapper/wiki/Translation#information-for-translators, I would say that the preferred way of contributing translations is through Weblate. What makes you contribute the Chinese translations through a GitHub pull request, please?

OK，thanks

**Comment by xianchb** [comment]
> Reading through https://github.com/OpenOrienteering/mapper/wiki/Translation#information-for-translators, I would say that the preferred way of contributing translations is through Weblate. What makes you contribute the Chinese translations through a GitHub pull request, please?

I am from China. I want to create a Chinese Manual. What should I do?

**Comment by jmacura** [comment]
> I am from China. I want to create a Chinese Manual. What should I do?

I guess it depends if you want to create a chinese version of the official manual, which comes bundled with the application, or your own independent manual.
The first one lives in its own repository: https://github.com/OpenOrienteering/mapper-manual so you can fork and translate it. I've started to do this for Czech, but don't have enough time to finish it...
The second one is quite up to you, if you don't want the manual to come bundled with the software.

**Comment by xianchb** [comment]
> > I am from China. I want to create a Chinese Manual. What should I do?
> 
> I guess it depends if you want to create a chinese version of the official manual, which comes bundled with the application, or your own independent manual.
> The first one lives in its own repository: https://github.com/OpenOrienteering/mapper-manual so you can fork and translate it. I've started to do this for Czech, but don't have enough time to finish it...
> The second one is quite up to you, if you don't want the manual to come bundled with the software.

Thank you for your reply. I'll have a try.

**Comment by lpechacek** [comment]
Misplaced pull request. Closing. I appreciate the attempt though. :)

**Pull request closed without merging**
