### PR TITLE
OCD: Silence false warnings on shifted rows pattern export

### PR DESCRIPTION
**Pull request by lpechacek**
I've been irritated by the warning about shifted rows pattern upon export to OCD for some time. While Mapper has a more flexible point pattern definition mechanism than the other program, there is one case where they match. The case typically occurs when and OCD is loaded to Mapper and then exported back to OCD. The import/export routines are at the level of completeness that this workflow can complete without excessive noise.

This patch detects when Mapper can successfully export shifted rows area pattern and silences the warning in this particular case. The code change does not look particularly beautiful and I'm considering it a "v1" with the possibility of rework.

### CODE REVIEW

**Comment by lpechacek** [comment]
@dg0yt, I'd be thankful for your review and comments.

**Comment by dg0yt** [comment]
Shall I pick this up? It is really worth pursueing.

**Comment by lpechacek** [comment]
Feel free to do so. The patch rework is currently low on my TODO list. Thanks!

**Comment by lpechacek** [comment]
And thanks for the review! I consider all the above valid points and I also share the long term ideas about export code improvements.

**Comment by lpechacek** [comment]
Reimplemented in the above-referenced pull request.

**Pull request closed without merging**
