### PR TITLE
images: Use trash bin for 'delete'

### PR DESCRIPTION
**Pull request by dg0yt**
This icon does not resemble the 'close' icon. Resolve a sub-item from #952.

### CODE REVIEW

**Comment by dg0yt** [comment]
Mobile:
delete-screenshot-mobile

Desktop:
delete-screenshot

**Comment by dg0yt** [comment]
@ollesmaps, @Zerbembasqwibo, @mlerjen, @lpechacek Opinions?

**Comment by Zerbembasqwibo** [comment]
Good. Maybe to put some stripes on in kind of this:
image

**Comment by dg0yt** [comment]
delete-screenshot

**Comment by ollesmaps** [comment]
That is great! Thank you!

**Pull request merged**
