### PR TITLE
Add tile size configuration to KMZ export

### PR DESCRIPTION
**Pull request by dg0yt**
...including single-image option.

Task: GH-1883 (Vikazimut compatibility)

### CODE REVIEW

**Comment by dg0yt** [comment]
Unbenannt

**Comment by lpechacek** [comment]
Apologies for off-topic upfront. I know virtually nothing about KMZ tiles, but working with the scribble layers, I dreamt about an adaptive scribble layer that would automatically add tiles as I paint instead of the current manual method where I add tiles when I need them. The scribble would be a single georeferenced layer then. Would KMZ be the direction to explore, or is there a better option, please?

**Comment by dg0yt** [comment]
@lpechacek I thought about this, too. It is clear that we need a tiled scribble layer. But I don't think the KMZ approach fits well for saving: it means updating a raster image file inside a big ZIP file via GDAL. Is this safe when an Android device is under pressure? I cannot use QSaveFile here. 
But the tiled scribble layer might benefit from how I enabled the loading off tiled KMZ files as templates. And WMS support will need tiles, too.

**Comment by mlerjen** [comment]
Loading and creating maptiles on demand from wms, xyz- datastructures mbtiles and alike would be huge.

**Comment by lpechacek** [comment]
> But I don't think the KMZ approach fits well for saving: it means updating a raster image file inside a big ZIP file via GDAL.

Good point. I missed the ZIP part. It disqualifies the idea for the moment.

> But the tiled scribble layer might benefit from how I enabled the loading off tiled KMZ files as templates. And WMS support will need tiles, too.

Good to know. This scribbling enhancement is low on my list but I'm still looking around if there is low hanging fruits. Thanks!

**Comment by dg0yt** [comment]
> > But I don't think the KMZ approach fits well for saving: it means updating a raster image file inside a big ZIP file via GDAL.
> 
> Good point. I missed the ZIP part. It disqualifies the idea for the moment.

I have to add that KML + raster tiles could also be used without zipping/KMZ.

> > But the tiled scribble layer might benefit from how I enabled the loading off tiled KMZ files as templates. And WMS support will need tiles, too.
> 
> Good to know. This scribbling enhancement is low on my list but I'm still looking around if there is low hanging fruits. Thanks!

That's why I do this KMZ stuff: it is low hanging fruits, with benefits for users(Google Earth, MapRun, Vikazimut) and for us  (exploring tile handling).

**Pull request merged**
